/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'viewCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'viewCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };